const fs = require('fs')
const packageJson = require('./package.json')
const defaultDark = require('./submodules/default/extensions/theme-defaults/themes/dark_vs.json')
const defaultDarkPlus = require('./submodules/default/extensions/theme-defaults/themes/dark_plus.json')
const nord = require('./submodules/nord/themes/nord.json')
const oneDark = require('./submodules/one-dark/themes/OneDark-Pro.json')

const COLORS = {
  hi: '#1a1a1a',
  mi: '#cecece',
  lo: '#212121',
  mo: '#262626',
  et: '#363636',
  tr: '#726c6b',
  oo: '#00000000',
  un: '#ff0000ff'
}

const UI = {
  colors: {
    'activityBar.background': COLORS.lo,
    'activityBar.dropBackground': COLORS.hi,
    'activityBar.foreground': COLORS.mi,
    'activityBar.inactiveForeground': COLORS.un,
    'activityBarBadge.background': COLORS.un,
    'activityBarBadge.foreground': COLORS.lo,
    'badge.background': COLORS.et,
    'badge.foreground': COLORS.lo,
    'breadcrumb.activeSelectionForeground': COLORS.un,
    'breadcrumb.background': COLORS.un,
    'breadcrumb.focusForeground': COLORS.un,
    'breadcrumb.foreground': COLORS.un,
    'breadcrumbPicker.background': COLORS.un,
    'button.background': COLORS.un,
    'button.foreground': COLORS.mi,
    'button.hoverBackground': COLORS.un,
    'debugExceptionWidget.background': COLORS.un,
    'debugExceptionWidget.border': COLORS.lo,
    'debugToolBar.background': COLORS.hi,
    'descriptionForeground': COLORS.un,
    'diffEditor.insertedTextBackground': COLORS.un,
    'diffEditor.removedTextBackground': COLORS.un,
    'dropdown.background': COLORS.hi,
    'dropdown.border': COLORS.hi,
    'dropdown.foreground': COLORS.mi,
    'editor.background': COLORS.mo,
    'editor.findMatchBackground': COLORS.un,
    'editor.findMatchHighlightBackground': COLORS.un,
    'editor.findRangeHighlightBackground': COLORS.un,
    'editor.focusedStackFrameHighlightBackground': COLORS.un,
    'editor.foreground': COLORS.mi,
    'editor.hoverHighlightBackground': COLORS.hi,
    'editor.inactiveSelectionBackground': COLORS.un,
    'editor.lineHighlightBackground': COLORS.et,
    'editor.lineHighlightBorder': COLORS.oo,
    'editor.rangeHighlightBackground': COLORS.un,
    'editor.selectionBackground': COLORS.et,
    'editor.selectionHighlightBackground': COLORS.un,
    'editor.snippetFinalTabstopHighlightBorder': COLORS.un,
    'editor.snippetTabstopHighlightBackground': COLORS.un,
    'editor.stackFrameHighlightBackground': COLORS.un,
    'editor.wordHighlightBackground': COLORS.un,
    'editor.wordHighlightStrongBackground': COLORS.un,
    'editorActiveLineNumber.foreground': COLORS.un,
    'editorBracketMatch.background': COLORS.lo,
    'editorBracketMatch.border': COLORS.un,
    'editorCodeLens.foreground': COLORS.un,
    'editorCursor.background': COLORS.et,
    'editorCursor.foreground': COLORS.mi,
    'editorError.foreground': COLORS.un,
    'editorGroup.border': COLORS.hi,
    'editorGroup.dropBackground': COLORS.hi,
    'editorGroupHeader.noTabsBackground': COLORS.lo,
    'editorGroupHeader.tabsBackground': COLORS.lo,
    'editorGroupHeader.tabsBorder': COLORS.hi,
    'editorGutter.addedBackground': COLORS.un,
    'editorGutter.background': COLORS.mo,
    'editorGutter.commentRangeForeground': COLORS.un,
    'editorGutter.deletedBackground': COLORS.un,
    'editorGutter.modifiedBackground': COLORS.un,
    'editorHint.foreground': COLORS.un,
    'editorHoverWidget.background': COLORS.hi,
    'editorHoverWidget.border': COLORS.hi,
    'editorIndentGuide.activeBackground': COLORS.un,
    'editorIndentGuide.background': COLORS.un,
    'editorInfo.foreground': COLORS.un,
    'editorLineNumber.activeForeground': COLORS.mi,
    'editorLineNumber.foreground': COLORS.et,
    'editorLink.activeForeground': COLORS.un,
    'editorMarkerNavigation.background': COLORS.un,
    'editorMarkerNavigationError.background': COLORS.un,
    'editorMarkerNavigationInfo.background': COLORS.un,
    'editorMarkerNavigationWarning.background': COLORS.un,
    'editorOverviewRuler.addedForeground': COLORS.un,
    'editorOverviewRuler.border': COLORS.hi,
    'editorOverviewRuler.bracketMatchForeground': COLORS.un,
    'editorOverviewRuler.commonContentForeground': COLORS.un,
    'editorOverviewRuler.currentContentForeground': COLORS.hi,
    'editorOverviewRuler.deletedForeground': COLORS.un,
    'editorOverviewRuler.errorForeground': COLORS.un,
    'editorOverviewRuler.findMatchForeground': COLORS.un,
    'editorOverviewRuler.incomingContentForeground': COLORS.hi,
    'editorOverviewRuler.infoForeground': COLORS.un,
    'editorOverviewRuler.modifiedForeground': COLORS.un,
    'editorOverviewRuler.rangeHighlightForeground': COLORS.un,
    'editorOverviewRuler.selectionHighlightForeground': COLORS.un,
    'editorOverviewRuler.warningForeground': COLORS.un,
    'editorOverviewRuler.wordHighlightForeground': COLORS.un,
    'editorOverviewRuler.wordHighlightStrongForeground': COLORS.un,
    'editorPane.background': COLORS.un,
    'editorRuler.foreground': COLORS.un,
    'editorSuggestWidget.background': COLORS.lo,
    'editorSuggestWidget.border': COLORS.hi,
    'editorSuggestWidget.foreground': COLORS.mi,
    'editorSuggestWidget.highlightForeground': COLORS.un,
    'editorSuggestWidget.selectedBackground': COLORS.un,
    'editorUnnecessaryCode.opacity': COLORS.un,
    'editorWarning.foreground': COLORS.un,
    'editorWhitespace.foreground': COLORS.un,
    'editorWidget.background': COLORS.lo,
    'editorWidget.border': COLORS.un,
    'errorForeground': COLORS.un,
    'extensionButton.prominentBackground': COLORS.un,
    'extensionButton.prominentForeground': COLORS.mi,
    'extensionButton.prominentHoverBackground': COLORS.un,
    'focusBorder': COLORS.hi,
    'foreground': COLORS.hi,
    'gitDecoration.addedResourceForeground': COLORS.un,
    'gitDecoration.conflictingResourceForeground': COLORS.un,
    'gitDecoration.deletedResourceForeground': COLORS.un,
    'gitDecoration.ignoredResourceForeground': COLORS.un,
    'gitDecoration.modifiedResourceForeground': COLORS.un,
    'gitDecoration.submoduleResourceForeground': COLORS.un,
    'gitDecoration.untrackedResourceForeground': COLORS.un,
    'gitlens.gutterBackgroundColor': COLORS.un,
    'gitlens.gutterForegroundColor': COLORS.un,
    'gitlens.gutterUncommittedForegroundColor': COLORS.un,
    'gitlens.lineHighlightBackgroundColor': COLORS.un,
    'gitlens.lineHighlightOverviewRulerColor': COLORS.un,
    'gitlens.trailingLineBackgroundColor': COLORS.un,
    'gitlens.trailingLineForegroundColor': COLORS.un,
    'input.background': COLORS.hi,
    'input.border': COLORS.hi,
    'input.foreground': COLORS.mi,
    'input.placeholderForeground': COLORS.mi,
    'inputOption.activeBorder': COLORS.un,
    'inputValidation.errorBackground': COLORS.un,
    'inputValidation.errorBorder': COLORS.un,
    'inputValidation.infoBackground': COLORS.un,
    'inputValidation.infoBorder': COLORS.un,
    'inputValidation.warningBackground': COLORS.un,
    'inputValidation.warningBorder': COLORS.un,
    'list.activeSelectionBackground': COLORS.et,
    'list.activeSelectionForeground': COLORS.lo,
    'list.dropBackground': COLORS.un,
    'list.errorForeground': COLORS.un,
    'list.focusBackground': COLORS.un,
    'list.focusForeground': COLORS.mi,
    'list.highlightForeground': COLORS.un,
    'list.hoverBackground': COLORS.hi,
    'list.inactiveFocusBackground': COLORS.un,
    'list.inactiveSelectionBackground': COLORS.et,
    'list.inactiveSelectionForeground': COLORS.mi,
    'list.invalidItemForeground': COLORS.un,
    'list.warningForeground': COLORS.un,
    'menu.background': COLORS.un,
    'menu.foreground': COLORS.un,
    'menu.selectionBackground': COLORS.un,
    'menu.selectionForeground': COLORS.un,
    'menu.separatorBackground': COLORS.un,
    'menubar.selectionBackground': COLORS.un,
    'menubar.selectionForeground': COLORS.un,
    'merge.border': COLORS.hi,
    'merge.commonContentBackground': COLORS.un,
    'merge.commonHeaderBackground': COLORS.un,
    'merge.currentContentBackground': COLORS.un,
    'merge.currentHeaderBackground': COLORS.un,
    'merge.incomingContentBackground': COLORS.un,
    'merge.incomingHeaderBackground': COLORS.un,
    'notificationCenterHeader.background': COLORS.un,
    'notificationLink.foreground': COLORS.un,
    'notifications.background': COLORS.un,
    'notifications.border': COLORS.un,
    'panel.background': COLORS.lo,
    'panel.border': COLORS.hi,
    'panel.dropBackground': COLORS.un,
    'panelTitle.activeBorder': COLORS.un,
    'panelTitle.activeForeground': COLORS.un,
    'panelTitle.inactiveForeground': COLORS.mi,
    'peekView.border': COLORS.un,
    'peekViewEditor.background': COLORS.lo,
    'peekViewEditor.matchHighlightBackground': COLORS.un,
    'peekViewEditorGutter.background': COLORS.lo,
    'peekViewResult.background': COLORS.lo,
    'peekViewResult.fileForeground': COLORS.un,
    'peekViewResult.lineForeground': COLORS.mi,
    'peekViewResult.matchHighlightBackground': COLORS.un,
    'peekViewResult.selectionBackground': COLORS.un,
    'peekViewResult.selectionForeground': COLORS.mi,
    'peekViewTitle.background': COLORS.hi,
    'peekViewTitleDescription.foreground': COLORS.mi,
    'peekViewTitleLabel.foreground': COLORS.un,
    'pickerGroup.border': COLORS.hi,
    'pickerGroup.foreground': COLORS.mi,
    'progressBar.background': COLORS.un,
    'scrollbar.shadow': COLORS.mo,
    'scrollbarSlider.activeBackground': `${COLORS.tr}99`,
    'scrollbarSlider.background': `${COLORS.tr}66`,
    'scrollbarSlider.hoverBackground': `${COLORS.tr}99`,
    'settings.checkboxBackground': COLORS.un,
    'settings.checkboxBorder': COLORS.un,
    'settings.checkboxForeground': COLORS.un,
    'settings.dropdownBackground': COLORS.un,
    'settings.dropdownBorder': COLORS.un,
    'settings.dropdownForeground': COLORS.un,
    'settings.dropdownListBorder': COLORS.un,
    'settings.headerForeground': COLORS.un,
    'settings.modifiedItemIndicator': COLORS.un,
    'settings.numberInputBackground': COLORS.un,
    'settings.numberInputBorder': COLORS.un,
    'settings.numberInputForeground': COLORS.un,
    'settings.textInputBackground': COLORS.un,
    'settings.textInputBorder': COLORS.un,
    'settings.textInputForeground': COLORS.un,
    'sideBar.background': COLORS.lo,
    'sideBar.border': COLORS.hi,
    'sideBar.dropBackground': COLORS.et,
    'sideBar.foreground': COLORS.mi,
    'sideBarSectionHeader.background': COLORS.hi,
    'sideBarSectionHeader.foreground': COLORS.mi,
    'sideBarTitle.foreground': COLORS.mi,
    'statusBar.background': COLORS.hi,
    'statusBar.border': COLORS.hi,
    'statusBar.debuggingBackground': COLORS.un,
    'statusBar.debuggingBorder': COLORS.un,
    'statusBar.debuggingForeground': COLORS.mi,
    'statusBar.foreground': COLORS.mi,
    'statusBar.noFolderBackground': COLORS.hi,
    'statusBar.noFolderBorder': COLORS.un,
    'statusBar.noFolderForeground': COLORS.mi,
    'statusBarItem.activeBackground': COLORS.un,
    'statusBarItem.hoverBackground': COLORS.un,
    'statusBarItem.prominentBackground': COLORS.hi,
    'statusBarItem.prominentHoverBackground': COLORS.un,
    'tab.activeBackground': COLORS.mo,
    'tab.activeBorder': COLORS.mo,
    'tab.activeBorderTop': COLORS.hi,
    'tab.activeForeground': COLORS.mi,
    'tab.activeModifiedBorder': COLORS.un,
    'tab.border': COLORS.hi,
    'tab.hoverBackground': COLORS.lo,
    'tab.inactiveBackground': COLORS.lo,
    'tab.inactiveForeground': COLORS.mi,
    'tab.inactiveModifiedBorder': COLORS.un,
    'tab.unfocusedActiveBorder': COLORS.un,
    'tab.unfocusedActiveBorderTop': COLORS.un,
    'tab.unfocusedActiveForeground': COLORS.mi,
    'tab.unfocusedActiveModifiedBorder': COLORS.un,
    'tab.unfocusedHoverBackground': COLORS.hi,
    'tab.unfocusedInactiveForeground': COLORS.mi,
    'tab.unfocusedInactiveModifiedBorder': COLORS.un,
    'terminal.ansiBlack': COLORS.hi,
    'terminal.ansiBlue': COLORS.un,
    'terminal.ansiBrightBlack': COLORS.un,
    'terminal.ansiBrightBlue': COLORS.un,
    'terminal.ansiBrightCyan': COLORS.un,
    'terminal.ansiBrightGreen': COLORS.un,
    'terminal.ansiBrightMagenta': COLORS.un,
    'terminal.ansiBrightRed': COLORS.un,
    'terminal.ansiBrightWhite': COLORS.un,
    'terminal.ansiBrightYellow': COLORS.un,
    'terminal.ansiCyan': COLORS.un,
    'terminal.ansiGreen': COLORS.un,
    'terminal.ansiMagenta': COLORS.un,
    'terminal.ansiRed': COLORS.un,
    'terminal.ansiWhite': COLORS.un,
    'terminal.ansiYellow': COLORS.un,
    'terminal.background': COLORS.lo,
    'terminal.border': COLORS.un,
    'terminal.foreground': COLORS.mi,
    'terminal.selectionBackground': COLORS.un,
    'textBlockQuote.background': COLORS.un,
    'textBlockQuote.border': COLORS.un,
    'textCodeBlock.background': COLORS.un,
    'textLink.activeForeground': COLORS.un,
    'textLink.foreground': COLORS.un,
    'textPreformat.foreground': COLORS.un,
    'textSeparator.foreground': COLORS.un,
    'titleBar.activeBackground': COLORS.lo,
    'titleBar.activeForeground': COLORS.mi,
    'titleBar.border': COLORS.lo,
    'titleBar.inactiveBackground': COLORS.lo,
    'titleBar.inactiveForeground': COLORS.mi,
    'walkThrough.embeddedEditorBackground': COLORS.lo,
    'widget.shadow': COLORS.un,
  }
}

// Override each theme's UI with Cameo's
const THEMES = {
  'default-dark': {
    type: 'dark',
    name: 'Cameo Dark (Visual Studio)',
    include: './_ui.json',
    tokenColors: defaultDark.tokenColors
  },
  'default-dark-plus': {
    type: 'dark',
    name: 'Cameo Dark+ (default dark)',
    include: './_ui.json',
    tokenColors: [...defaultDark.tokenColors, ...defaultDarkPlus.tokenColors]
  },
  nord: {
    type: 'dark',
    name: 'Cameo Nord',
    include: './_ui.json',
    tokenColors: nord.tokenColors
  },
  'one-dark': {
    type: 'dark',
    name: 'Cameo One Dark',
    include: './_ui.json',
    tokenColors: oneDark.tokenColors
  }
}

// Export the UI
fs.writeFile(
  `./themes/_ui.json`,
  JSON.stringify(UI, null, 2),
  'utf8',
  (msg, err) => {
    if (err) {
      console.error(err)
    }

    console.log('Exported _ui.json')
  }
)

// Export the themes
Object.keys(THEMES).forEach(key => {
  const theme = THEMES[key]
  const fileName = `cameo-${key}-color-theme.json`
  fs.writeFile(
    `./themes/${fileName}`,
    JSON.stringify(theme, null, 2),
    'utf8',
    (msg, err) => {
      if (err) {
        console.error(err)
      }

      console.log(`Exported ${fileName}`)
    }
  )
})

// Put themes in package.json
packageJson.contributes.themes = Object.keys(THEMES).map(key => ({
  label: THEMES[key].name,
  uiTheme: 'vs-dark',
  path: `./themes/cameo-${key}-color-theme.json`
}))

// Export package.json
fs.writeFile(
  `./package.json`,
  JSON.stringify(packageJson, null, 2),
  'utf8',
  (msg, err) => {
    if (err) {
      console.error(err)
    }

    console.log('Exported package.json')
  }
)
